version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true

exclude_patterns:
- "lib/vendor/"
