// BHO5.idl : IDL source for BHO5
//

// This file will be processed by the MIDL tool to
// produce the type library (BHO5.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,	
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(2A99AF00-021E-4F08-BC81-77F5DFCB4D6E),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IRESBHO : IDispatch{
};
[
	uuid(1D79FD4E-045B-4CE8-8FBE-73ACA827BF5F),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{BB019707-32A8-45EA-AAFA-F6620AFA38CA}")
]
library BHO5Lib
{
	importlib("stdole2.tlb");
	[
		uuid(BB019707-32A8-45EA-AAFA-F6620AFA38CA)		
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(E3A3FEA8-E3D0-4888-BDAF-BC6691564288)		
	]
	coclass RESBHO
	{
		[default] interface IRESBHO;
	};
};

